// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimuladorPC.Data;

#nullable disable

namespace SimuladorPC.Data.Migrations
{
    [DbContext(typeof(SimuladorPcContext))]
    partial class SimuladorPcContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimuladorPC.Domain.Entities.Gabinete", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Altura")
                        .HasColumnType("float");

                    b.Property<int>("BaiasExternas")
                        .HasColumnType("int");

                    b.Property<int>("BaiasInternas")
                        .HasColumnType("int");

                    b.Property<double>("Comprimento")
                        .HasColumnType("float");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Largura")
                        .HasColumnType("float");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuportePlacaMae")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TemFiltrosDePoeira")
                        .HasColumnType("bit");

                    b.Property<bool>("TemJanela")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gabinetes");
                });

            modelBuilder.Entity("SimuladorPC.Domain.Entities.WaterCooler", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadeFans")
                        .HasColumnType("int");

                    b.Property<string>("SocketsCompativeis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TamanhoRadiador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WaterCoolers");
                });

            modelBuilder.Entity("SimuladorPC.Domain.Entities.Gabinete", b =>
                {
                    b.OwnsOne("SimuladorPC.Domain.Entities.Iluminacao", "Iluminacao", b1 =>
                        {
                            b1.Property<string>("GabineteId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("CorFixa")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("IsArgb")
                                .HasColumnType("bit");

                            b1.Property<bool>("IsRgb")
                                .HasColumnType("bit");

                            b1.Property<bool>("TemIluminacao")
                                .HasColumnType("bit");

                            b1.HasKey("GabineteId");

                            b1.ToTable("Gabinetes");

                            b1.WithOwner()
                                .HasForeignKey("GabineteId");
                        });

                    b.Navigation("Iluminacao")
                        .IsRequired();
                });

            modelBuilder.Entity("SimuladorPC.Domain.Entities.WaterCooler", b =>
                {
                    b.OwnsOne("SimuladorPC.Domain.Entities.Iluminacao", "Iluminacao", b1 =>
                        {
                            b1.Property<string>("WaterCoolerId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("CorFixa")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("IsArgb")
                                .HasColumnType("bit");

                            b1.Property<bool>("IsRgb")
                                .HasColumnType("bit");

                            b1.Property<bool>("TemIluminacao")
                                .HasColumnType("bit");

                            b1.HasKey("WaterCoolerId");

                            b1.ToTable("WaterCoolers");

                            b1.WithOwner()
                                .HasForeignKey("WaterCoolerId");
                        });

                    b.Navigation("Iluminacao");
                });
#pragma warning restore 612, 618
        }
    }
}
